### ISSUE TITLE
Possible typos in various database values (RockType, Notes, County)

### ISSUE THREAD

**Issue by cmrRose** [WGNHS/LSLC-Web-App#15]
Fixing typos will help users find all the data that should come up in a search. After collecting a list of samples here, we'll ask Brad or Pete to fix the typos. 

Samples id# 1167, 3325, 3326

**Comment by cmrRose** [comment]
Sample #1800: "Chlortie slate"

**Comment by cmrRose** [comment]
sample #278318 has just a space in the notes field.

**Comment by cmrRose** [comment]
sample #3488 typo in notes field

**Comment by cmrRose** [comment]
Sample IDs 5378 and 5383 seem to be in Ashland County, but their County value in the samples table is 'Iron'

**Comment by BradfordTG** [comment]
Sample #3488 has no typo--it's the name of the river from the notebook.

**Comment by BradfordTG** [comment]
5378 and 5383 are indeed in Ashland Co. There must be a glitch in the algorithm that generated the county--I'm not sure if I can just type in the correct county, or if that will mess things up. In any case, the process for generating counties should be checked.

**Comment by cmrRose** [comment]
I'll close this and move the counties problem to its own issue: https://github.com/WGNHS/LSLC-Web-App/issues/66
