### ISSUE TITLE
Odd-looking section boundaries 

### ISSUE THREAD

**Issue by cmrRose** [WGNHS/LSLC-Web-App#18]
Many sections seem to have one corner cut off. 
Here's an image from the UP near Marquette. 
![image](https://cloud.githubusercontent.com/assets/6922132/23527207/abaea5e0-ff5a-11e6-9857-1f89434f0dda.png)

**Comment by schoep** [comment]
So the base map service looks OK but the overlying query results are odd? Looks like they each are missing one vertex.

**Comment by cmrRose** [comment]
![image](https://cloud.githubusercontent.com/assets/6922132/23812543/97c06d56-05a0-11e7-9f85-002d0f86bc0c.png)
Again, more missing vertices in the UP

**Comment by cmrRose** [comment]
Since switching over to Leaflet, I haven't seen this issue.
