### ISSUE TITLE
Add a Ledgers table

### ISSUE THREAD

**Issue by cmrRose** [WGNHS/LSLC-Web-App#30]
From the "Specimen Catalog and Other Ledgers" table in Access. 
Should provide information on the six Lithological Description books. That's all I can link to at the moment, unless there's a way (and a reason) to link a sample to a specimen catalog.

**Comment by schoep** [comment]
[Added.](http://geodata.wgnhs.uwex.edu/arcgis/rest/services/lslc/lslc/MapServer/6)

**Comment by cmrRose** [comment]
@schoep  We will need a BookId (or perhaps LedgerBookId?) field to be added to the Lithology table, so we can: 
Search Lithology for the sample ID --> find the BookId in the Lithology table --> search for that value in the Ledgers table.

**Comment by schoep** [comment]
Yeah I noted that as an issue while updating the services. Thanks for mentioning it here.

**Comment by schoep** [comment]
@cmrRose Lithology now has BookId
