### ISSUE TITLE
Reference field notebooks only by their notebookNum. (not NotebookID)

### ISSUE THREAD

**Issue by cmrRose** [WGNHS/LSLC-Web-App#31]
Add the NotebookNum field to the samples table. 

Then I will update the SQL to search that field and update all references/labels to call it 'notebook number.

**Comment by schoep** [comment]
@cmrRose there is now "NotebookNum" in [http://geodata.wgnhs.uwex.edu/arcgis/rest/services/lslc/lslc/MapServer/1] that should be the actual notebook number. I'll let you close this when confirmed.
