### ISSUE TITLE
There should be 1:1 HandSamples:Samples 

### ISSUE THREAD

**Issue by cmrRose** [WGNHS/LSLC-Web-App#35]
Brad says that every sample should have Hand Sample information, even if we don't still have the rock itself. The hand sample's catalog number is needed to connect the sample to the field notes (catalog number is written in the margin of the field notebook).  

Could the samples table please have: 
- a field indicating hand sample catalog number (even if the physical sample is unavailable, EVERY sample should have a unique value for this)
- a field indicating whether the physical hand sample is available (true/false or 1/null) (Seems like the current HandSampleCount field is equivalent to this? Maybe just name it HandSampleAvailable instead? Or just leave it if that's extra work).

After talking to Brad, we agreed that if these two fields are in the samples table, we have no need for an independent HandSamples table, since we are not interested in listing the cabinet and drawer on the webpage.

**Comment by schoep** [comment]
"HandSampleCatalogNumber" has been added to [Sample](http://geodata.wgnhs.uwex.edu/arcgis/rest/services/lslc/MapServer/6)

**Comment by cmrRose** [comment]
Need to revise the regular expression that tests for valid input in the sample record page. 
Currently, it rejects values with letters.

**Comment by cmrRose** [comment]
Changed the regex to test for letters and numbers. Made the search case-insensitive for the letters.
