### ISSUE TITLE
Test solution for image file access

### ISSUE THREAD

**Issue by schoep** [WGNHS/LSLC-Web-App#4]
At least a test solution for storing images. We will need to store: 
- full-resolution thin section images (2 per thin section)
- 200px tall thumbnails for: thin section images, field notebook covers (as many as 500?), lith. description book covers (6) 

Additionally, each image or thumbnail's url or file path will need to be referenced in a field in a table: field for cover image in the notebooks table, and four fields in the thin sections table (full-resolution PPL, full-resolution XPL, thumbnail PPL, thumbnail XPL).

**Comment by schoep** [comment]
@cmrRose some image files for Wisconsin have been staged on the internal test server...
Full resolution JPEGs are [here](http://mp-web2t/lslc/assets/thin-section/images)
Zoomify folders are [here](http://mp-web2t/lslc/assets/thin-section/zoomify)
The naming convention is the catalog thin section number with a suffix of "xpl" or "ppl", e.g. 724ppl. There were no images for 11 slides. If you can provide a thumbnailing script I can run that on my local copy of the files and then stage those on the server.

**Comment by cmrRose** [comment]
@schoep  I'll do the Photoshop script tomorrow.

**Comment by cmrRose** [comment]
@schoep Are we happy with our image hosting solutions? Satisfied that this will scale to the larger collection when we add thin sections from other states?

**Comment by schoep** [comment]
Aaron thinks we'll be OK. I should have the full set of images publically-accessible for testing week of Apr 10.

**Comment by schoep** [comment]
@cmrRose update on image file access...

* thin section zoomify (all): https://geodata.wgnhs.uwex.edu/lake-superior-legacy/assets/thin-section-zoomify/
* thin section full res (all): https://geodata.wgnhs.uwex.edu/lake-superior-legacy/assets/thin-section-images/
* notebook thumbs (188): https://geodata.wgnhs.uwex.edu/lake-superior-legacy/assets/notebook-thumbs/
* thin section thumbs (Wisc): https://geodata.wgnhs.uwex.edu/lake-superior-legacy/assets/thin-section-thumbs/

TO-DO: Give access to Caroline to create thumbs for full set of thin sections (could be over 8 hours).

**Comment by cmrRose** [comment]
Example full URLs: 
- thin section full res: https://geodata.wgnhs.uwex.edu/lake-superior-legacy/assets/thin-section-images/2802xpl.jpg
- thin section thumbnail: https://geodata.wgnhs.uwex.edu/lake-superior-legacy/assets/thin-section-thumbs/2802xpl_thumb.jpg 
- notebook thumbnail: https://geodata.wgnhs.uwex.edu/lake-superior-legacy/assets/notebook-thumbs/fieldNotebook7_cover_thumb.jpg
