### ISSUE TITLE
Please update the Notes Section of Samples Table. 

### ISSUE THREAD

**Issue by cmrRose** [WGNHS/LSLC-Web-App#40]
Brad recently fixed the formatting of links (anchor tags) in the notes field.

**Comment by schoep** [comment]
@cmrRose Samples has been refreshed

**Comment by cmrRose** [comment]
The format of the links in the notes field still doesn't quite work correctly. It's appending the link as a string to the LSLC base URL- I don't know why. Will investigate.

**Comment by cmrRose** [comment]
We might need to use single quotes instead of double quotes within the notes section... since the server returns the entire notes string enclosed in double quotes.

**Comment by cmrRose** [comment]
@schoep Could you replace all double quotes in the notes field with single quotes? 

Thanks

**Comment by cmrRose** [comment]
Just try replacing the double quotes with single quotes in one sample row just to test it... try the sample with catalog # 988

**Comment by schoep** [comment]
@cmrRose single quotes now within the markup for 988 and it looks like it might work. Please confirm and I will update for all.

**Comment by cmrRose** [comment]
@schoep Yes, it looks like that works great for me. Thanks

**Comment by cmrRose** [comment]
All have been updated.
