### ISSUE TITLE
Mixed Content error 

### ISSUE THREAD

**Issue by cmrRose** [WGNHS/LSLC-Web-App#41]
I created a live online branch hosted on github here: https://wgnhs.github.io/LSLC-Web-App/filterSamples.html 
It doesn't load unless you disable the secure connection, due to a "Mixed Content Issue." You have to click "load unsafe scripts" in every tab. This seems to stem from the fact that it requests info from the map service through http, not https. 

This is a problem because we shouldn't be forcing users to disable protections/security settings in their browser to get the page to work. I'm not quite sure what we need to do about it.  @schoep can you investigate, or should I?

**Comment by cmrRose** [comment]
"Mixed Content: The page at 'https://wgnhs.github.io/LSLC-Web-App/filterSamples.html' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://geodata.wgnhs.uwex.edu/arcgis/rest/services/lslc/MapServer/0/query?r…tryEnvelope&spatialRel=esriSpatialRelIntersects&geometryPrecision=6&f=json'. This content should also be served over HTTPS."

**Comment by cmrRose** [comment]
For my reference: https://help.github.com/articles/securing-your-github-pages-site-with-https/

**Comment by schoep** [comment]
We are in the process of applying a cert to the production web server. When that is complete I'll make adjustments to use HTTPS for the services.

**Comment by schoep** [comment]
SSL/TLS is enabled on both the GIS server and web server. I will work on redirecting all traffic to HTTPS.

**Comment by cmrRose** [comment]
It looks like this is resolved, with all images coming from https.
