### ISSUE TITLE
map sections not displaying

### ISSUE THREAD

**Issue by cmrRose** [WGNHS/LSLC-Web-App#45]
I consistently see that many map sections don't show up, like here in Michigan:  
![image](https://cloud.githubusercontent.com/assets/6922132/24621684/f0408022-1867-11e7-98b2-e00e811aa597.png)

until I zoom into the area: 
![image](https://cloud.githubusercontent.com/assets/6922132/24621706/0aeeabec-1868-11e7-9caa-86d1956a1ef4.png)

**Comment by schoep** [comment]
@cmrRose When I completely remade service last week I forgot to adjust the max query response. I just moved it from 1k to 5k so you should see max results.

**Comment by cmrRose** [comment]
Yes! That appears to have fixed it!
