### ISSUE TITLE
duplicate entries in the Samples table 

### ISSUE THREAD

**Issue by cmrRose** [WGNHS/LSLC-Web-App#60]
I'm getting pairs of duplicate CatalogNumber and SampleID values (paired with unique QbjectID values) 

![image](https://cloud.githubusercontent.com/assets/6922132/25025875/9e97b448-2069-11e7-8ec2-a655f0ca37d0.png)

It shows up in a query of the table through this interface too: 
http://geodata.wgnhs.uwex.edu/arcgis/rest/services/lslc/MapServer/6/query?where=SampleId+%3D+210&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&relationParam=&outFields=*&returnGeometry=true&maxAllowableOffset=&geometryPrecision=&outSR=&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&returnDistinctValues=false&f=html

![image](https://cloud.githubusercontent.com/assets/6922132/25025964/07abe152-206a-11e7-80e1-5f36f037f033.png)

**Comment by cmrRose** [comment]
Possible culprit is Section#204140 , which seems to be a tiny island. 
![image](https://cloud.githubusercontent.com/assets/6922132/25026099/92d64e16-206a-11e7-82c2-f052100ec59d.png)

Might have duplicates of the samples in Section #204136, the large section on the mainland. 
![image](https://cloud.githubusercontent.com/assets/6922132/25026123/bfa6bfd4-206a-11e7-9f31-e20e3fd86870.png)

**Comment by cmrRose** [comment]
![image](https://cloud.githubusercontent.com/assets/6922132/25026181/01895ccc-206b-11e7-850c-60d48de90fd7.png)

![image](https://cloud.githubusercontent.com/assets/6922132/25026198/0aa9f53c-206b-11e7-997b-8399d927cd01.png)

**Comment by schoep** [comment]
I'll check the sections geometry, but will likely need to merge features to multipart.

**Comment by schoep** [comment]
@cmrRose an update of both the PLSS Sections polygons and Sample table is ready to deploy. The PLSS sections were dissolved to multipart features so no more many-to-many joins. One major change is the new field "PlssId" to replace the ambiguous "SectionId". This new field appears in the both the PLSS Sections layer and the Sample table. Other fields in the PLSS Section have been renamed and cleaned-up for clarity.  I'm waiting to deploy until you are ready to update the code to handle the new field.

**Comment by schoep** [comment]
@cmrRose the new services have been deployed. Let me know if you need any changes and I'll let you close the issue when ready.

**Comment by cmrRose** [comment]
The duplicate entries in the samples table are gone, thanks to you cleaning up the polygons. 

The field designating section ID is now named PlssId in both the samples table and the sections layer.

In the samples table, the SampleId field has now become the esriFieldTypeOID field or OBJECTID field. This is the field that is returned in response to a query for ids.
